/control/cout/ignoreThreadsExcept 0
/control/verbose 0
/run/verbose 0
/tracking/verbose 0

#/target/setWidth 1.0
/shell/setShellType 1
/run/initialize
#/process/inactivate nKiller
/run/reinitializeGeometry

#/geometry/test/run
#/geometry/test/tolerance 1 nm
#/run/setCut 10 cm  
#/run/setCutForAGivenParticle gamma 10 cm

/analysis/setFileName AGMACRONBSR1m
/run/printProgress 200000
/run/initialize
/run/beamOn 100000000

